fixed format test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -35,4 +35,11 @@ jobs:
           go-version: '1.23.0'
 
       - name: Run test formatting
-        run: go test -z $(go fmt ./...)
+         run: |
+        go fmt ./...
+        if [ $? -ne 0 ]; then
+          echo "go fmt failed"
+          exit 1
+        else
+          echo "Formatting check passed."
+        fi
